#!/bin/bash
# YouTube Research Cron - Runs daily at 6 AM
# Fetches top 20 YouTube videos for $1B solopreneur goals

API_KEY="AIzaSyDe245nWkV2HXdfmqJxhrBhYVigijgBO3s"
REPO_DIR="/home/itsaslamautomations/.openclaw/workspace/Daily-Working-Space"
OUTPUT_DIR="$REPO_DIR/YouTubeResearch"

DATE=$(date +%Y-%m-%d)
OUTPUT_FILE="$OUTPUT_DIR/${DATE}.md"

# Search queries aligned with $1B solopreneur goal
QUERIES=(
  "AI automation agency business 2026"
  "solopreneur SaaS build 2026"
  "vibe coding app builder 2026"
  "OpenClaw use cases money"
  "Nano Banana Pro business"
  "micro SaaS profitable 2026"
  "AI agents make money 2026"
  "one person business AI"
)

echo "# YouTube Research - $(date +%B\ %d,\ %Y)

> Generated: $(date)
> Focus: \$1B Solopreneur Goals

---

## Top 20 YouTube Videos (Last 48 Hours)

" > "$OUTPUT_FILE"

count=1

for query in "${QUERIES[@]}"; do
  echo "Searching: $query"
  
  results=$(curl -s "https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=5&q=$query&order=date&type=video&key=$API_KEY" 2>/dev/null)
  
  echo "$results" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    for item in data.get('items', [])[:3]:
        snippet = item.get('snippet', {})
        title = snippet.get('title', 'N/A')
        channel = snippet.get('channelTitle', 'N/A')
        video_id = item.get('id', {}).get('videoId', '')
        published = snippet.get('publishedAt', '')[:10]
        print(f'### {title}')
        print(f'**Channel:** {channel}')
        print(f'**Published:** {published}')
        print(f'**Link:** https://www.youtube.com/watch?v={video_id}')
        print()
except: pass
" >> "$OUTPUT_FILE" 2>/dev/null
done

echo "---

## Recommended YouTube Channels

| Channel | Why Follow |
|---------|------------|
| **Liam Ottley** | AI agency business, automation |
| **Dan Martell** | AI agents, SaaS growth |
| **Moon Dev** | OpenClaw use cases |
| **Greg Isenberg** | Vibe coding trends |
| **Wholesale Ted** | Nano Banana Pro, beginner |
| **Starter Story** | Real solopreneur case studies |
| **Paul J Lipsky** | Nano Banana Pro deep dives |
| **Matthew Berman** | OpenClaw tutorials |
| **Anik Singal** | One-person business |
| **TK Kader** | AI SaaS ideas |

---

*Generated by OpenClaw Cron Job*
*Focus: Building \$1B Solopreneur Company*" >> "$OUTPUT_FILE"

# Commit and push
cd "$REPO_DIR"
git add YouTubeResearch/
git commit -m "docs: YouTube research $(date +%Y-%m-%d)" 2>/dev/null
git push origin main 2>/dev/null

echo "Done! File: $OUTPUT_FILE"
